declare namespace styles {
	const oGrid2Columns: string
	const oGrid3Columns: string
	const oGrid4Columns: string
	const oGrid5Columns: string
	const oGrid6Columns: string
	const oGrid7Columns: string
	const oGrid8Columns: string
	const oGrid9Columns: string
	const oGrid10Columns: string
	const oGrid11Columns: string
	const oGrid12Columns: string
	const oSpan1: string
	const oSpan2: string
	const oSpan3: string
	const oSpan4: string
	const oSpan5: string
	const oSpan6: string
	const oSpan7: string
	const oSpan8: string
	const oSpan9: string
	const oSpan10: string
	const oSpan11: string
	const oSpan12: string
	const oSpan1Med: string
	const oSpan2Med: string
	const oSpan3Med: string
	const oSpan4Med: string
	const oSpan5Med: string
	const oSpan6Med: string
	const oSpan7Med: string
	const oSpan8Med: string
	const oSpan9Med: string
	const oSpan10Med: string
	const oSpan11Med: string
	const oSpan12Med: string
	const oSpan1Lg: string
	const oSpan2Lg: string
	const oSpan3Lg: string
	const oSpan4Lg: string
	const oSpan5Lg: string
	const oSpan6Lg: string
	const oSpan7Lg: string
	const oSpan8Lg: string
	const oSpan9Lg: string
	const oSpan10Lg: string
	const oSpan11Lg: string
	const oSpan12Lg: string
}
export default styles
